name: quiz_bank
description: A comprehensive Flutter package providing true/false quiz questions with categories, difficulty levels, and easy customization. Perfect for educational apps, trivia games, and learning platforms.
version: 1.0.0
homepage: https://github.com/droidbg/quiz_bank
repository: https://github.com/droidbg/quiz_bank
issue_tracker: https://github.com/droidbg/quiz_bank/issues
documentation: https://pub.dev/documentation/quiz_bank/latest/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
